refactor(contracts): implement time filter for slashing
pnetwork-association/dao-v2-contracts pull request #20
Opened 2023-11-10 10:31 UTC by oliviera9

Refs: #pnetwork/177

2023-11-21 12:07 UTC, wernervoncroy requested changes

2023-11-21 12:07 UTC, wernervoncroy commented on contracts/core/RegistrationManager.sol
> +        if (_lastResumeTimestamp[actor] != uint256(0) && slashTimestamp < _lastResumeTimestamp[actor])
why uint256(0) and not 0?

2023-11-21 12:07 UTC, wernervoncroy commented on contracts/core/RegistrationManager.sol
> +        if (_lastSlashTimestamp[actor] != uint256(0) && slashTimestamp < _lastSlashTimestamp[actor] + 1 hours)
why reading _lastSlashTimestamp twice? reading a variable from storage has a cost.

Suggestion:
```sol
uint64 timestamp = _lastSlashTimestamp[actor]
if( timestamp!= uint256(0) && slashTimestamp < timestamp + 1 hours) ...
```

2023-11-21 12:07 UTC, wernervoncroy commented on contracts/core/RegistrationManager.sol
> +        _lastSlashTimestamp[actor] = 0;
Why is it needed only in light resume and not also in hard resume? i would use 0 instead of block.timestamp

2023-11-21 12:40 UTC, oliviera9 commented on contracts/core/RegistrationManager.sol
> +        _lastSlashTimestamp[actor] = 0;
Do you mean block.timestamp instead of 0?

2023-11-21 12:41 UTC, oliviera9 commented on contracts/core/RegistrationManager.sol
> +        if (_lastSlashTimestamp[actor] != uint256(0) && slashTimestamp < _lastSlashTimestamp[actor] + 1 hours)
Ovb due to my limited knowledge of solidity.

2023-11-21 14:30 UTC, oliviera9 commented on contracts/core/RegistrationManager.sol
> +        if (_lastResumeTimestamp[actor] != uint256(0) && slashTimestamp < _lastResumeTimestamp[actor])
Fixed, using directly 0 now.

2023-11-21 18:01 UTC, gitmp01 reviewed
Just a comment that I think it's needed, then LGTM

2023-11-21 18:01 UTC, gitmp01 commented on contracts/core/RegistrationManager.sol
> +            revert Errors.ActorAlreadyResumed(lastResumeTimestamp, slashTimestamp);
If I got this right, you are preventing slashes that have not been received yet to slash again in case a sentinel resume itself before. If that's correct, please add a comment that took me a bit to see the it :bulb:

2023-11-21 18:01 UTC, gitmp01 commented on contracts/core/RegistrationManager.sol
> +            revert Errors.ActorAlreadyResumed(lastResumeTimestamp, slashTimestamp);
I was wondering if you could do everything with just a single `lastTimestamp[]` array...but probably wouldn't be as much readable

2023-11-21 18:01 UTC, gitmp01 commented on test/RegistrationManager.test.js
> +      .to.revertedWithCustomError(registrationManager, 'ActorAlreadyResumed')
:+1:

2023-11-30 12:45 UTC, oliviera9 commented on contracts/core/RegistrationManager.sol
> +            revert Errors.ActorAlreadyResumed(lastResumeTimestamp, slashTimestamp);
Comment added.

What are you willing to achieve with the array? isn't the mapping a better option for this?

2023-11-30 14:32 UTC, gitmp01 commented on contracts/core/RegistrationManager.sol
> +            revert Errors.ActorAlreadyResumed(lastResumeTimestamp, slashTimestamp);
Yeah I was just raising the question if we could save little bit of gas, but I wouldn't mind for now

2023-11-30 15:37 UTC, oliviera9 commented on contracts/core/RegistrationManager.sol
> +        _lastSlashTimestamp[actor] = 0;
Zero is needed because otherwise we would enter the `lastSlashTimestamp + 1 hours` check which should be executed against a real slashing.

2023-12-01 08:31 UTC, oliviera9 commented on contracts/core/RegistrationManager.sol
> +        _lastSlashTimestamp[actor] = 0;
Added for `hardResume` as well

2023-12-01 08:36 UTC, gitmp01 approved these changes
LGTM

2023-12-01 09:17 UTC, merged