Add RewardsManager contract to manage DAO incentives for stakers
pnetwork-association/dao-v2-contracts pull request #24
Opened 2024-01-29 10:41 UTC by oliviera9

1. The new contract will receive tokens from whitelisted addresses, e.g. DAO voting contract.
2 . A permission-less function can be called by anyone to register for rewards for a specific epoch.
3. One will be eligible for rewards if he has voted at least once in the specified epoch.
4. Once a reward is registered for a user, the contract will mint daoPNT tokens for that user so they will account in his balance.
5. Finally, the user will be able to withdraw his tokens _after one year._

2024-02-12 16:24 UTC, gitmp01 requested changes
No major issues, few open question marks though

2024-02-12 16:24 UTC, gitmp01 commented on contracts/core/RewardsManager.sol
> +        return (epochStartDate, epochEndDate);
Use timestamps since date may be confusing:
```suggestion
        uint256 epochStartTs = startFirstEpochTimestamp + (epoch * epochDuration);
        uint256 epochEndTs = epochStartDate + epochDuration - 1;
        return (epochStartTs, epochEndTs);
```

2024-02-12 16:24 UTC, gitmp01 commented on contracts/interfaces/IRewardsManager.sol
Shall we put a comment for each function describing the purpose plus a use case?

2024-02-12 16:24 UTC, gitmp01 commented on contracts/interfaces/IRewardsManager.sol
For posterity...

2024-02-12 16:24 UTC, gitmp01 commented on test/RewardsManager.test.js
> +  })
:+1:

2024-02-12 16:24 UTC, gitmp01 commented on test/RewardsManager.test.js
> +    const amount = (ethers.parseUnits('660000') * 10n) / 100n
you mean 10% of the total supply of daoPNT? not much clear in my opinion

2024-02-12 16:24 UTC, gitmp01 commented on test/RewardsManager.test.js
> +    expect(pntRewardsManagerBalancePost).to.be.eq(pntRewardsManagerBalancePre + amount)
This is very similar (if not the same) to the previous test, factor out?

2024-02-12 16:24 UTC, gitmp01 commented on contracts/core/RewardsManager.sol
> +    function registerRewardsForEpoch(uint16 epoch, address[] calldata stakers) external {
The usage of this function doesn't convince me for the following reasons:
 1. The poor guy who will call it the first time have to pay for all the registration of the other stakers, which is not ideal
 2. Same would happen when no one has registered the rewards for X number of consecutive epochs
 3. The stakers list has to be given before hand, not super handy from the user perspective I guess

Why do you think this way is better than having a 

```suggestion
    function registerRewardsForEpoch(uint16 epoch) external {
```

which would just register the reward for `msg.sender` in case it belongs to the stakers?

2024-02-12 16:24 UTC, gitmp01 commented on test/RewardsManager.test.js
> +    await dandelionVoting.newVote()
A comment saying what the status would help readability:
```js
// 0 absent
// 1 yes
// 2 no
```

2024-02-12 16:24 UTC, gitmp01 commented on test/RewardsManager.test.js
> +  it('should not be able to register for rewards without voting', async () => {
Seeing what the test does, I think there's a mistake:
```suggestion
  it('should not be able to claim for rewards without voting', async () => {
```

2024-02-13 17:34 UTC, oliviera9 commented on contracts/core/RewardsManager.sol
> +    function registerRewardsForEpoch(uint16 epoch, address[] calldata stakers) external {
1. Why? The idea is to permit anyone to call it. In particular, at the beginning we may call it as pNetwork. That would make things easier for stakers. If someone is left out, he can call the function specifying its address only.

2024-02-13 17:35 UTC, oliviera9 commented on contracts/core/RewardsManager.sol
> +    function registerRewardsForEpoch(uint16 epoch, address[] calldata stakers) external {
2. why? do you mean we should have a function automatically registering for all epochs?

2024-02-13 18:05 UTC, gitmp01 commented on contracts/core/RewardsManager.sol
> +    function registerRewardsForEpoch(uint16 epoch, address[] calldata stakers) external {
Sorry I got confused, I don't know why I was conviced this had to be done for each staker and for each epoch which is clearly not the case with this one. Looking again at the code everything looks good!

2024-02-14 10:28 UTC, oliviera9 commented on contracts/core/RewardsManager.sol
> +    function registerRewardsForEpoch(uint16 epoch, address[] calldata stakers) external {
3. > The stakers list has to be given before hand

That's exactly why I implemented this function. There is no list of stakers on chain. So it needs to be built off-chain. Anyway, I don't expect users to call that function. Instead I expect we'll run a script calling that function with a maintained list of stakers.

2024-02-14 10:28 UTC, oliviera9 commented on contracts/interfaces/IRewardsManager.sol
Absolutely! I just wanted to have the entire logic reviewed, just to be sure I will not comment function that might change.

2024-02-14 10:28 UTC, oliviera9 commented on test/RewardsManager.test.js
> +    await dandelionVoting.newVote()
Done

2024-02-14 10:28 UTC, oliviera9 commented on test/RewardsManager.test.js
> +  it('should not be able to register for rewards without voting', async () => {
Indeed, you can't register if you didn't vote. As a consequence, you won't be able to claim as you haven't been registered.

2024-02-14 10:28 UTC, oliviera9 commented on test/RewardsManager.test.js
> +    const amount = (ethers.parseUnits('660000') * 10n) / 100n
Correct, but notice this can be any value. 660000 is just the sum of the minted daoPNT tokens in the test, and I take the 10% as the subsequent numbers are easier (see subsequent assessments of lockedRewardByEpoch)

2024-02-14 10:56 UTC, gitmp01 commented on test/RewardsManager.test.js
> +  it('should not be able to register for rewards without voting', async () => {
I think the phrase can be misinterpreted since I initially got that someone (randomguy?) can't register (hence call `registerRewardsForEpoch`) without voting. 
Probably worth clarifying a bit the statement with
```suggestion
  it('should not be able to claim for rewards without being registered', async () => {
```

2024-02-14 11:24 UTC, oliviera9 commented on test/RewardsManager.test.js
> +    expect(pntRewardsManagerBalancePost).to.be.eq(pntRewardsManagerBalancePre + amount)
Done

2024-02-14 12:29 UTC, oliviera9 commented on contracts/core/RewardsManager.sol
> +        return (epochStartDate, epochEndDate);
Done

2024-02-14 12:31 UTC, oliviera9 commented on test/RewardsManager.test.js
> +  it('should not be able to register for rewards without voting', async () => {
I just rephrased the test description as the test is more general.

2024-02-14 13:10 UTC, gitmp01 commented on contracts/interfaces/IRewardsManager.sol
cool :+1:

2024-02-14 14:44 UTC, gitmp01 approved these changes
LGTM

2024-02-14 14:44 UTC, gitmp01 commented on contracts/core/RewardsManager.sol
> +        return (epochStartTimestamp, epochEndTimestamp);
:+1:

2024-02-14 14:44 UTC, gitmp01 commented on test/constants.js
> +  VOTE_STATUS: {
:+1:

2024-02-14 14:44 UTC, gitmp01 commented on contracts/core/LendingManager.sol
> +        if (numberOfVotes == 0 || numberOfVotes > votedVotes) revert Errors.NotPartecipatedInGovernanceAtEpoch(epoch);
To me be sounds better `NoGovernanceParticipationAtEpoch`, but it's just a matter of preference

2024-02-14 14:44 UTC, gitmp01 commented on test/LendingManager.test.js
> +      .withArgs(1)
:+1:

2024-02-14 14:44 UTC, gitmp01 commented on test/RewardsManager.test.js
> +    await assertDaoPntBalances(['0', '0', '0', '0'])
Nice refactoring

2024-02-14 14:44 UTC, gitmp01 commented on test/RewardsManager.test.js
> +    await tokenManager.mint(pntHolder4.address, ethers.parseUnits('10000'))
I see this as a quick way to populate each holder balance with daoPNT, it's just a matter of keeping the test simple, right?

2024-02-14 14:44 UTC, gitmp01 commented on test/RewardsManager.test.js
> +    await tokenManager.mint(pntHolder4.address, ethers.parseUnits('10000'))
If yes, maybe worth putting that into a comment above these lines

2024-02-14 14:44 UTC, gitmp01 commented on test/RewardsManager.test.js
> +    const amount = (ethers.parseUnits('660000') * 10n) / 100n
Gotcha

2024-02-14 14:46 UTC, oliviera9 commented on test/RewardsManager.test.js
> +    await tokenManager.mint(pntHolder4.address, ethers.parseUnits('10000'))
Yeah, just a way to avoid introducing a StakingManager

2024-02-14 14:46 UTC, oliviera9 commented on test/RewardsManager.test.js
> +    await tokenManager.mint(pntHolder4.address, ethers.parseUnits('10000'))
I'll add a comment

2024-02-14 15:04 UTC, gitmp01 commented on test/RewardsManager.test.js
> +    await tokenManager.mint(pntHolder4.address, ethers.parseUnits('10000'))
Thinking about it, I'd add a small test having also the staking manager for giving the daoPNT, since that's the real use case in the end. It may just work or bring up something interesting

2024-02-14 15:06 UTC, gitmp01 commented on test/RewardsManager.test.js
> +  it('should not be able to register for rewards without voting', async () => {
Yeah looks better now

2024-02-14 18:28 UTC, oliviera9 commented on test/RewardsManager.test.js
> +    await tokenManager.mint(pntHolder4.address, ethers.parseUnits('10000'))
This would be an integration test. I will add it to dao.test.js once I'll have a deployed RewardsManager.

2024-02-14 18:31 UTC, oliviera9 commented on contracts/core/LendingManager.sol
> +        if (numberOfVotes == 0 || numberOfVotes > votedVotes) revert Errors.NotPartecipatedInGovernanceAtEpoch(epoch);
I just reused an error introduced by Ale. I would leave it as it is.

2024-02-16 14:55 UTC, merged